# Generated by Django 2.1.7 on 2019-03-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textOfComment', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=20)),
            ],
        ),
    ]
